### ISSUE TITLE
Basic Installation instruction?

### ISSUE THREAD

**Issue by r4mp4l** [bhaugen/foodnetwork#1]
Happy Tuesday,

May I have basic installation instructions? 

I will be experimenting on a webfaction account.

Thank you.

Gaurav

**Comment by bhaugen** [comment]
We don't have any written installation instructions, and I can't reliably write anything off the top of my head. But if you get a webfaction account, I'll set it up for you and take notes while I do it, and then we will have some.

Might take awhile, I have not done this for a couple of years. But if you want to use our demo site for experimentation, I'll clean out the database and you can start from scratch. That would be quicker. Nobody else is using it now, and I always keep a backup, so we won't lose anything.

**Comment by bhaugen** [comment]
That demo site no longer exists. See updated readme.
